# Generated by Django 4.2.9 on 2024-01-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ocrtool", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="ImageUpload",),
    ]
