# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ar_SNwEXhTSZhNmxUi52cpE_Yd7HeztK
"""

from bs4 import BeautifulSoup
import requests
import pandas as pd

class ProductScraper:
    def __init__(self):
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
        }

    def get_data(self, query):
        url = "https://www.ssg.com/search.ssg?target=all&query=" + query

        response = requests.get(url, headers=self.headers)
        soup = BeautifulSoup(response.text, 'lxml')

        if response.status_code != 200:
            print(response.status_code)
            return

        product_names = []
        prices = []
        product_urls = []

        for li in soup.find_all('li', class_='cunit_t232'):
            product_name = li.find('div', class_='title').text.strip()
            price = li.find('em', class_='ssg_price').text.strip()
            product_url = 'https://www.ssg.com' + li.find('a', class_='clickable')['href']

            product_names.append(product_name)
            prices.append(price)
            product_urls.append(product_url)

        data = {'Product Name': product_names, 'Price': prices, 'Product URL': product_urls}
        df = pd.DataFrame(data)
        df = df.sort_values(by='Price')

        return df