# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ar_SNwEXhTSZhNmxUi52cpE_Yd7HeztK
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

class CoupangScraper:
    def __init__(self, query):
        self.query = query
        self.url = "https://www.coupang.com/np/search?component=&q=" + query + "&channel=user"
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3',
            "Accept-Language": "ko-KR,ko;q=0.8,en-US;q=0.5,en;q=0.3"
        }
        self.products = []

    def scrape(self):
        response = requests.get(self.url, headers=self.headers)
        soup = BeautifulSoup(response.text, 'html.parser')
        li_tags = soup.find_all('li', attrs={'class':'search-product'})

        for li in li_tags:
            name = li.find('div', class_='name').text
            price = li.find('strong', class_='price-value').text
            link = "https://www.coupang.com" + li.find('a', class_='search-product-link')['href']
            self.products.append((name, price, link))

    def to_dataframe(self):
        df = pd.DataFrame(self.products, columns=['Product_Name', 'Price', 'Product_Link'])
        df['Price'] = df['Price'].str.replace(',', '').astype(int)
        return df