# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ar_SNwEXhTSZhNmxUi52cpE_Yd7HeztK
"""

from bs4 import BeautifulSoup
import requests
import pandas as pd

class MusinsaScraper:
    def __init__(self, query):
        self.query = query
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
        }
        self.url = "https://www.musinsa.com/search/musinsa/integration?q=" + self.query

    def scrape(self):
        response = requests.get(self.url, headers=self.headers)
        soup = BeautifulSoup(response.text, 'lxml')

        result = []
        goods_links = soup.find_all('a', attrs={'name': 'goods_link'})
        prices = soup.find_all('p', attrs={'class': 'price'})

        for link, price in zip(goods_links, prices):
            title = link.get('title')
            price_text = price.find('del')

            if price_text is not None:
                price_text.extract()

            price_text = price.text.strip().replace('원', '').replace(',', '')
            link = link.get('href')

            result.append((title, price_text, link))

        df = pd.DataFrame(result, columns=['Product_Name', 'Price', 'Product_Link'])
        df['Price'] = df['Price'].str.replace(',', '').astype(int)
        return df